// |||||||||||| GAME STATES
const Game = {
    INVALID: -1,
    LOADING: 0,
    MAIN_MENU: 1,
    STORY_MENU: 2,
    PLAYING: 3,
    OVER: 4,
};

// |||||||||||| FPS (FRAMES PER SECOND)
const FPS = 30;

// |||||||||||| DIFFERENT TILESETS
const Tile = {
    SIZE_OTHERS: 0,     // SPRITES (64 x 64, ETC.)
    SIZE_16:     1,     // MAP TILES (16 x 16)
};

// |||||||||||| MAP BLOCK IDENTIFIER
const Block = {
    EMPTY: 0,
    DARK_BROWN_BLOCK: 64,
    DARK_BROWN_SLOPE_UPWARDS_1: 66,
    DARK_BROWN_SLOPE_UPWARDS_2: 67,
    DARK_BROWN_SLOPE_DOWNWARDS_1: 68,
    DARK_BROWN_SLOPE_DOWNWARDS_2: 69,
    DARK_BROWN_SLOPE_DOWNWARDS_REVERSED_1: 75,
    DARK_BROWN_SLOPE_DOWNWARDS_REVERSED_2: 76,
    DARK_BROWN_SLOPE_UPWARDS_REVERSED_1: 77,
    DARK_BROWN_SLOPE_UPWARDS_REVERSED_2: 78,
    SPIKES_FLOOR: 86,
    SPIKES_CEILING: 87,
    SPIKES_LEFTWARDS: 88,
    SPIKES_RIGHTWARDS: 89,
    VERTICAL_CHAIN_1: 94,
    GRAY_BLOCK: 95,
    VERTICAL_CHAIN_2: 103,
    OPEN_DOOR_CHUNK_1: 115,
    CLOSED_DOOR_CHUNK_1: 116,
    VERTICAL_CHAIN_3: 121,
    OPEN_DOOR_CHUNK_2: 124,
    CLOSED_DOOR_CHUNK_2: 125,
    LAVA: 127,
};

// |||||||||||| SPRITE TYPE IDENTIFIER (ID)
const SpriteID = {
    PLAYER: 0,
    CHAOTIC_HUMAN_BOW: 1,
    CHAOTIC_HUMAN_SWORD: 2,
    FAST_WORM: 3,
    HELL_BAT_ACID: 4,
    HELL_BAT_HAND_TO_HAND: 5,
    POTION_GREEN: 6,
    POTION_BLUE: 7,
    BACKGROUND_IMG_CAVE_SECT_1: 8,
    THE_ERUDITE_HUD: 9,
    RAGE_BAR_CONTAINER: 10,
    RAGE_BAR_CONTENT: 11,
    BACKGROUND_IMG_MAIN_MENU: 12,
    NEW_GAME_ICON: 13,
    STORY_ICON: 14,
    HIGH_SCORES_ICON: 15,
    CONTROLS_ICON: 16,
    BACKGROUND_IMG_STORY_MENU: 17,
};

// |||||||||||| SPRITE STATE IDENTIFIER (DIRECTION)
const State = {
    // |||||||| PLAYER (1), FAST WORM, HELL BAT (ACID)
    UP: 0,
    LEFT: 1,
    DOWN: 2,
    RIGHT: 3,

    // |||||||| PLAYER (2)
    UP_ATTACK: 4,
    LEFT_ATTACK: 5,
    DOWN_ATTACK: 6,
    RIGHT_ATTACK: 7,
    AWAKENING: 8,

    // |||||||| CHAOTIC HUMAN (BOW)
    DOWN_2: 0,
    DOWN_ATTACK_2: 1,
    LEFT_2: 2,
    LEFT_ATTACK_2: 3,
    RIGHT_2: 4,
    RIGHT_ATTACK_2: 5,
    UP_2: 6,
    UP_ATTACK_2: 7,

    // |||||||| CHAOTIC HUMAN (SWORD | 1), HELL BAT (HAND-TO-HAND)
    DOWN_3: 0,
    LEFT_3: 1,
    RIGHT_3: 2,
    UP_3: 3,

    // |||||||| CHAOTIC HUMAN (SWORD | 2)
    DYING: 4,

    // |||||||| POTION (GREEN & BLUE), BACKGROUND IMAGES, ICONS, THE ERUDITE (HUD), RAGE BAR (CONTAINER & CONTENT)
    STILL: 0,
};

// |||||||||||| EXPORTS
export { Game, FPS, SpriteID, State, Tile, Block };