// |||||||||||| GAME STATES
const Game = {
    INVALID: -1,
    LOADING: 0,
    LOADING_MAIN_MENU: 1,
    MAIN_MENU: 2,
    LOADING_STORY_MENU: 3,
    STORY_MENU: 4,
    LOADING_CONTROLS_MENU: 5,
    CONTROLS_MENU: 6,
    LOADING_HIGH_SCORES_MENU: 7,
    HIGH_SCORES_MENU: 8,
    LOADING_LEVEL_1: 9,
    PLAYING_LEVEL_1: 10,
    LOADING_GAME_OVER: 11,
    OVER: 12,
};

// |||||||||||| FPS (FRAMES PER SECOND)
const FPS = 30;

// |||||||||||| DIFFERENT TILESETS
const Tile = {
    SIZE_OTHERS: 0,     // SPRITES (64 x 64, ETC.)
    SIZE_16:     1,     // MAP TILES (16 x 16)
};

// |||||||||||| MAP BLOCK IDENTIFIER
const Block = {
    EMPTY: 0,
    DARK_BROWN_BLOCK: 64,
    SPIKES_FLOOR: 86,
    SPIKES_CEILING: 87,
    SPIKES_LEFTWARDS: 88,
    SPIKES_RIGHTWARDS: 89,
    GRAY_BLOCK: 95,
    OPEN_DOOR_CHUNK_1: 115,
    CLOSED_DOOR_CHUNK_1: 116,
    OPEN_DOOR_CHUNK_2: 124,
    CLOSED_DOOR_CHUNK_2: 125,
    LAVA_1: 127,
    LAVA_2: 128,
    DARK_BROWN_SLOPE_UPWARDS: 129,
    DARK_BROWN_SLOPE_DOWNWARDS: 130,
    DARK_BROWN_SLOPE_UPWARDS_REVERSED: 131,
    DARK_BROWN_SLOPE_DOWNWARDS_REVERSED: 132,
};

// |||||||||||| SPRITE TYPE IDENTIFIER (ID)
const SpriteID = {
    PLAYER: 0,
    CHAOTIC_HUMAN_BOW: 1,
    CHAOTIC_HUMAN_SWORD: 2,
    FAST_WORM: 3,
    HELL_BAT_ACID: 4,
    HELL_BAT_HAND_TO_HAND: 5,
    POTION_GREEN: 6,
    POTION_BLUE: 7,
    BACKGROUND_IMG_LEVEL_1: 8,
    THE_ERUDITE_HUD: 9,
    RAGE_BAR_CONTAINER: 10,
    RAGE_BAR_CONTENT: 11,
    BACKGROUND_IMG_MAIN_MENU: 12,
    NEW_GAME_ICON: 13,
    STORY_ICON: 14,
    HIGH_SCORES_ICON: 15,
    CONTROLS_ICON: 16,
    BACKGROUND_IMG_STORY_MENU: 17,
    BACKGROUND_IMG_CONTROLS_MENU: 18,
    UP_ARROW_KEY: 19,
    DOWN_ARROW_KEY: 20,
    LEFT_ARROW_KEY: 21,
    RIGHT_ARROW_KEY: 22,
    SPACE_KEY: 23,
    A_LETTER_KEY: 24,
    S_LETTER_KEY: 25,
    SKULL: 26,
    BACKGROUND_IMG_HIGH_SCORES_MENU: 27,
    MAGICAL_ORB: 28,
    ARROW: 29,
    ACID: 30,
    SUN: 31,
};

// |||||||||||| SPRITE STATE IDENTIFIER (DIRECTION)
const State = {
    // |||||||| PLAYER (1), FAST WORM, HELL BAT (ACID | 1)
    UP: 0,
    LEFT: 1,
    DOWN: 2,
    RIGHT: 3,

    // |||||||| PLAYER (2)
    UP_ATTACK_HAND_TO_HAND: 4,
    LEFT_ATTACK_HAND_TO_HAND: 5,
    DOWN_ATTACK_HAND_TO_HAND: 6,
    RIGHT_ATTACK_HAND_TO_HAND: 7,
    LEFT_ATTACK_MAGICAL_ORB: 8,
    RIGHT_ATTACK_MAGICAL_ORB: 9,
    AWAKENING: 10,
    UP_STILL: 11,
    LEFT_STILL: 12,
    DOWN_STILL: 13,
    RIGHT_STILL: 14,
    LEFT_JUMP: 15,
    RIGHT_JUMP: 16,

    // |||||||| CHAOTIC HUMAN (BOW)
    LEFT_ATTACK_2: 0,
    RIGHT_ATTACK_2: 1,

    // |||||||| CHAOTIC HUMAN (SWORD | 1), HELL BAT (HAND-TO-HAND)
    DOWN_3: 0,
    LEFT_3: 1,
    RIGHT_3: 2,
    UP_3: 3,

    // |||||||| CHAOTIC HUMAN (SWORD | 2)
    DYING: 4,

    // |||||||| HELL BAT (ACID | 2)
    UP_DEAD: 4,
    LEFT_DEAD: 5,
    DOWN_DEAD: 6,
    RIGHT_DEAD: 7,

    // |||||||| ARROW
    LEFT_4: 0, 
    RIGHT_4: 1, 

    // |||||||| ACID, MAGICAL ORB, POTION (GREEN & BLUE), BACKGROUND IMAGES, ICONS, THE ERUDITE (HUD), RAGE BAR (CONTAINER & CONTENT)
    STILL: 0,

    // |||||||| ALL
    OFF: -1,
};

// |||||||||||| KEYBOARD KEY CODES
const Key = {
    ENTER: 13,    
    ESCAPE: 27,    
    JUMP: 32,    
    LEFT: 37,    
    UP: 38,    
    RIGHT: 39,
    DOWN: 40,
    A: 65,    
    S: 83,    
};

// |||||||||||| ACCELERATION
const GRAVITY = 150;

// |||||||||||| PARTICLE TYPE IDENTIFIER (ID)
const ParticleID = {
    RAGE_SYMBOL: 0,
    CONTROLS_MENU_SPARKLE: 1,
    CHECKPOINT: 2,
    LAVA: 3,
};

// |||||||||||| PARTICLE STATE IDENTIFIER
const ParticleState = {
    ON: 0,
    FADE: 1,
    OFF: -1,
};

// |||||||||||| EXPORTS
export {
    Game,
    FPS,
    SpriteID,
    State,
    Tile,
    Block,
    Key,
    GRAVITY,
    ParticleID,
    ParticleState,
};